config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'rooms#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :events
  # , only: [:index, :new, :show, :edit, :destroy]

  # get '/rooms/:id', to: 'rooms#show'
  # # get 'events', to: 'events#index'
  # post '/events', to: 'events#index'
  # delete '/events/:id', to: 'events#destroy'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direct_message.rb
# frozen_string_literal: true

class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true #これにより無記入投稿とエンター長押しの連続投稿の2つが同時に防げる
  # ブロードキャスト
  after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room
  validates :title, presence: true #これにより無記入投稿とエンター長押しの連続投稿の2つが同時に防げる
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
  has_many :events, dependent: :destroy
  # refile使用
  attachment :image
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
  has_many :events
  # refile使用
  attachment :image
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email image])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_in_path_for(_resource)
    users_path
  end
end

app/controllers/direct_messages_controller.rb
# frozen_string_literal: true

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_room, only: %i[index create show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    # @events = Event.all
    @events = Event.where(room_id: @room.id)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :color, :allday, :user_id, :room_id).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_room, only: [:index, :new, :edit]
  before_action :set_event, only: [:show, :edit, :update, :destroy] #パラメータのidからレコードを特定するメソッド
  before_action :move_to_index, except: [:index]


  def index
    @users = User.where.not(id: current_user)
  end

  def show
    # RoomsController
    @room = Room.find(params[:id])
    # ルームが作成されているかどうか
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @direct_messages = @room.direct_messages #このルームのメッセージを全て取得
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end

    # EventsController
    @events = Event.where(room_id: @room.id)
  end

  def new
    @event = Event.new
  end

  def create
    @room = Room.create(name: "Chat room")
    # entryにログインユーザーを作成
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    # entryにparamsユーザーを作成
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    # redirect_to room_path(@room.id)

    # EventsController
    @event = Event.new(event_params)
      respond_to do |format|
      if @event.save
        # redirect_to template: 'rooms/show' and return
      # else
      #   redirect_to action: :show 
          format.html { redirect_to template: 'rooms/show', location: @event }
          format.json { render :show, status: :created, location: @event }
      else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @room.destroy
    room = Room.find_by(params[:id])
    room.destroy
    redirect_to users_rooms_path

    # EventsController
    @event.destroy
    respond_to do |format|
      format.html { redirect_to room_path(@room.id), location: @event }
      # events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_room
    @room = Room.find_by(params[:id])
  end

  def set_event
    @event = Event.find_by(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :color, :allday, :user_id, :room_id).merge(user_id: current_user.id, room_id: @room.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    # チャット
    if user_signed_in?
      # Entry内のuser_idがcurrent_userと同じEntry
      @currentUserEntry = Entry.where(user_id: current_user.id)
      # Entry内のuser_idがMYPAGEのparams.idと同じEntry
      @userEntry = Entry.where(user_id: @user.id)
      # @user.idとcurrent_user.idが同じでなければ
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            # もしcurrent_user側のルームidと＠user側のルームidが同じであれば存在するルームに飛ぶ
            if cu.room_id == u.room_id
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        # ルームが存在していなければルームとエントリーを作成する
        unless @isRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/direct_messages_helper.rb
# frozen_string_literal: true

module DirectMessagesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/direct_messages/_direct_message.html.erb
<%# <p class='<%= direct_message.id %>
<div class='dm-form' >
  <%# <%= attachment_image_tag direct_message.user, :image, class: "dm-form_image", fallback: "no_image.jpeg", size: "30x30" %>
  <div class='dm-form_name'><%= direct_message.user.name %></div>
  <div class="dm-form_content"><%= direct_message.content %></div>
  <div class='dm-form_time'><%= direct_message.created_at.strftime("%H:%M") %></div>
</div>
<%# </p> %>

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |form| %>
<%# , url: room_path(@room.id) %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル %>
    <%= form.text_field :title, class: 'input-form' %>
  </div>

  <div class="field">
    <%= form.label :開始 %>
    <%= form.datetime_select :start_date, class: 'input-form' %>
  </div>

  <div class="field">
    <%= form.label :終了 %>
    <%= form.datetime_select :end_date, class: 'input-form' %>
  </div>

  <div class="field">
    <%# <%= form.label :roomnumber %>
    <%= form.hidden_field :room_id, :value => params[:room_id] %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%# <%= form.hidden_field :room_id, :value => @room.id %> 
  </div>

  <div class="actions">
    <%= form.submit :イベント追加, class: 'event-link' %>
  </div>
<% end %>

app/views/events/_index.html.erb
<div class='leftbar'>
  <div class='todo'>予定リスト</div>

  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>開始</th>
        <th>終了</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.start_date.strftime("%m/%d %H:%M") %></td>
          <td><%= event.end_date.strftime("%m/%d %H:%M") %></td>
          <td><%= link_to '表示', event %></td>
          <td><%= link_to '変更', edit_event_path(event) %></td>
          <td><%= link_to '消去', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'イベント追加', new_event_path, class: 'eventadd' %>

  <div id= "calendar" ></div>
  
</div>

app/views/events/edit.html.erb
<h1>イベント変更</h1>

<%= render 'form', event: @event %>

<%= link_to '表示', @event, class: 'action-btn' %> 
<%= link_to '戻る', room_path(@event.room_id), class: 'action-btn' %>

app/views/events/index.html.erb
<%= render 'shared/header' %>
<div class='leftbar'>
  <div class='todo'>予定リスト</div>

  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>開始</th>
        <th>終了</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.start_date.strftime("%m/%d %H:%M") %></td>
          <td><%= event.end_date.strftime("%m/%d %H:%M") %></td>
          <td><%= link_to '表示', event %></td>
          <td><%= link_to '変更', edit_event_path(event) %></td>
          <td><%= link_to '消去', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'イベント追加', new_event_path, class: 'eventadd' %>

  <div id= "calendar" ></div>
  
</div>

app/views/events/new.html.erb
<h1>新しいイベント</h1>

<%= render 'form', event: @event %>

<%= link_to '戻る', room_path(@event.room_id), class: 'action-btn' %>

app/views/events/show.html.erb
<p class='field'>
  <label>タイトル:</label>
  <div class='disp-form'>
    <%= @event.title %>
  </div>
</p>

<p class='field'>
  <label>開始:</label>
  <div class='disp-form'>
    <%= @event.start_date.strftime("%m/%d %H:%M") %>
  </div>
</p>

<p class='field'>
  <label>終了:</label>  
  <div class='disp-form'>
    <%= @event.end_date.strftime("%m/%d %H:%M") %>
  </div>
</p>

<%= link_to '変更', edit_event_path(@event), class: 'action-btn' %> |
<%= link_to '戻る', room_path(@event.room_id), class: 'action-btn' %>

app/views/events_sub/edit.html.erb
<% events.each do |event| %>
  <div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-nm">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">スケジュール編集</h4>
        </div>
        <div class="modal-body">
          <div  class="col">
            <%= form_with(model: event, url: users_event_path(event), method: :put) do |f| %>
              <p>
                <span>タイトル</span>
                <span id="inputTitle" value=""><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
              </p>
              <span>開始日時</span>
              <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
              <span>終了日時</span>
              <span><%= f.datetime_field  :end, placeholder: "XXXX-XX-XX", class:"field" %></span>
              <span><br>
                詳細
                <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %>
              </span>
              <div class="modal-footer">
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "編集する", class: "btn btn-primary" %>
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events_sub/index.html.erb
<div id="calendar"></div>

app/views/events_sub/show.html.erb
<h3 class="text-center">カレンダー</h3>
<!-- カレンダーの表示 -->
<div id="calendar"></div>
<!-- もしユーザーがログインしていたら -->
<% if user_signed_in? %>
  <!-- ページのparams.idがログインユーザー.idと同じなら -->
  <% if @user.id == current_user.id %>
    <div id="inputScheduleForm" class="modal fade" tabindex="-1">
      <div class="modal-dialog modal-nm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">スケジュール登録</h4>
          </div>
          <div class="modal-body">
            <%= form_with model: @event, url: events_path do |f| %>
              <div class="col">
                <p>
                  <span>タイトル</span>
                  <span><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                </p>
                <span>開始日時</span>
                <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                <span>終了日時</span>
                <span><%= f.datetime_field :end, placeholder: "XXXX-XX-XX", class:"field" %></span><br>
                <span>詳細
                <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %></span>
              </div>
              <div class="modal-footer">
                <%= f.submit "登録する", class: "btn btn-primary" %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<!-- 編集 ------------------------------------------------------------------>
    <div id="inputEditForm">
      <%= render 'events/edit', events: @events %>
    </div>
  <% end %>
<% end %>

<script>
  // CRUDを行う際にCSRF対策のtokenを発行
  $(document).ready(function() {
    var prepare = function(options, originalOptions, jqXHR) {
      var token;
      if (!options.crossDomain) {
        token = $('meta[name="csrf-token"]').attr('content');
        if (token) {
          return jqXHR.setRequestHeader('X-CSRF-Token', token);
        }
      }
    };
  }
  )

    // カレンダー表示
    $('#calendar').fullCalendar ({
      header: {
        left: 'prev,next today',
        center: 'month,agendaWeek,agendaDay',
        right: 'title'
      },

      buttonText: {
        prev: "<",
        next: ">"
      },

      timezone: 'UTC',
      events: '/users/events.json',
      navLinks: true,
      selectable: true,
      selectHelper: true,
      // 日付クリック
      dayClick : function ( date , jsEvent , view ) {
        $('#inputScheduleForm').modal('show');
      },

      // event クリックで編集、削除
      eventClick : function(event, jsEvent , view) {
        jsEvent.preventDefault();
        $(`#inputScheduleEditForm${event.id}`).modal('show');
      },

      eventMouseover : function(event, jsEvent , view) {
        jsEvent.preventDefault();
      }
    })

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <title>ChatCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <body data-turbolinks="false">
    <%= yield %>
  </body>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>

</html>

app/views/rooms/index.html.erb
<%= render 'shared/header' %>
<div class='main'>
  <div class='leftmain'>
    <%= render 'shared/welcom' %>
  </div>

  <div class='rigtmain'>
    <% if user_signed_in? %>
      <%= render template: 'users/index' %>
      <% else %>
      <%= render 'shared/subbar'%>
      <%# <%= render 'users/show' %> 
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= render template: 'events/index' %>

<div class='chatbar'>
  <h1><%= @room.name %></h1>
  <h4>参加者 : 
    <% @entries.each do |e| %>
      <div class='room_user'>
        <%= link_to "@#{e.user.name}", user_path(e.user_id) %>
      </div>
    <% end %>
  </h4>
  <div id="direct_messages" data-room_id="<%= @room.id %>">
    <%= render @direct_messages %>
  </div>

  <form>
    <input type="text" id="chat-input" data-behavior="room_speaker" class='chat-input-form' placeholder='メッセージを入力'>
  </form>

  <%= link_to "トップに戻る", rooms_path, class: 'user_link' %>

  <%= link_to "ユーザー一覧に戻る", users_path, class: 'user_link' %>
</div>

app/views/shared/_header.html.erb
<header>
  <div class='leftbar'>
    <div class='theme'>Chat_Calendar</div>
  </div>
  <div class='rigtbar'>
    <div class='sign'>
      <% if user_signed_in? %>
      <div class='sign_user'>
        <%= current_user.name %><br>
        <%= current_user.email %><br>
      </div>
        <%= link_to 'プロフ変更', edit_user_registration_path, class: 'sign_btn' %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'sign_btn' %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: 'sign_btn' %>
        <%= link_to "ログイン", new_user_session_path, class: 'sign_btn' %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_subbar.html.erb
<div class = 'subbar'>
  <h1>ようこそ!</h1>
  <h1>カレンダーチャットへ</h1>
  <h1>予定を共有しよう!</h1>
</div>

app/views/shared/_welcom.html.erb
<div class = 'welcome'>
  <p>※イメージ</p>
  <span><%= link_to image_tag(asset_path('calendar.png'), alt:'calendar_chat', size:"555x497"), root_path %></span>
</div>

app/views/users/_index.html.erb
<h3>ユーザ一覧</h3>
<h3>チャットする友達をお選びください</h3>


<% @users.each do |user| %>
  <%= link_to "ユーザ名:#{user.name}", user_path(user.id), class: 'user_link' %>
<% end %>

<%= link_to "トップに戻る", rooms_path, class: 'user_link' %>

app/views/users/index.html.erb
<%# <%= render 'shared/header' %> 
<h1>予定を共有しよう！</h1>
<h3>ユーザ一覧</h3>
<h3>共有する友達をお選びください</h3>

<% @users.each do |user| %>
  <%= link_to "ユーザ名:#{user.name}", user_path(user.id), class: 'user_link' %>
<% end %>

<%= link_to "トップに戻る", rooms_path, class: 'user_link' %>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<h3>ユーザー詳細</h3>

<div class='room_select'>
  <% if user_signed_in? %>
    <% unless @user.id == current_user.id %>
    <!-- 既にroomが存在していれば既存のroomへ -->
      <% if @isRoom == true %>
    <!-- roomに飛べるようにする -->
        <%= link_to "チャットへGo!", room_path(@roomId), id: "dm_submit", class: 'user_link' %>
      <% else %>
    <!-- roomが存在していなければroomを作成する  -->
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", id: "dm_submit", class: 'user_link' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", rooms_path, class: 'user_link' %>